name: cicd-Lara-dev
on:
  workflow_dispatch:
env:
  AZURE_WEBAPP_NAME: "as-laraeunp"
  SOLUTION_FILE: "PG.LARA.sln"
jobs:
  build-and-deploy:
    # Dynamically set the job name based on the application name
    name: ${{ matrix.webjob-name }}
    runs-on: windows-latest
    strategy:
      matrix:
         webjob-path: ['PG.LARA.ValidationSummaryReport.WebJob', 'PG.LARA.GenerateValidationSummary.WebJob', 'PG.LARA.GeneratesJDATemplates.WebJob']
         webjob-name: ['NotifyMetadataValidation', 'GenerateValidationSummary', 'GenerateTMSOutputTemplates']
         webjob-type: ['Triggered', 'Triggered', 'Triggered']
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1
      - name: Restore NuGet Packages
        run: nuget restore ${{ env.SOLUTION_FILE }}
      - name: Build Application (${{ matrix.webjob-name }})
        run: |
          msbuild ${{ matrix.webjob-path }}/PG.LARA.${{ matrix.webjob-name }}.WebJob.csproj `
            /p:DeployOnBuild=true `
            /p:OutputPath=./publish/App_Data/jobs/${{ matrix.webjob-type }}/DEV-${{ matrix.webjob-name }}}
