name: cicd-dev
on:
  push:
    branches:
      - cicd
  workflow_dispatch:
env:
  AZURE_WEBAPP_NAME: "as-laraeunp"
  SOLUTION_FILE: "PG.LARA.sln"
jobs:
  build-and-deploy:
    # Dynamically set the job name based on the application name
    name: ${{ matrix.name }}
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - { path: PG.LARA.ValidationSummaryReport.WebJob, name: NotifyMetadataValidation, type: Triggered }
          - { path: PG.LARA.GenerateValidationSummary.WebJob, name: GenerateValidationSummary, type: Triggered }
          - { path: PG.LARA.GeneratesJDATemplates.WebJob, name: GenerateTMSOutputTemplates, type: Triggered }
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1
      - name: Create Publish Directories
        run: |
          mkdir -p ".\publish\App_Data\jobs\${{ matrix.type }}\DEV-${{ matrix.name }}"
          Copy-Item -Path ".\PG*" -Destination ".\publish\App_Data\jobs\${{ matrix.type }}\DEV-${{ matrix.name }}" -Recurse -Force
        shell: pwsh
      - name: Compress WebJob Files
        run: |
          Compress-Archive -Path ".\publish\App_Data\jobs\${{ matrix.type }}\DEV-${{ matrix.name }}/*" `
            -DestinationPath ".\publish\App_Data\jobs\${{ matrix.type }}\DEV-${{ matrix.name }}.zip"
          dir .\publish\App_Data\jobs\${{ matrix.type }}\\DEV-${{ matrix.name }}
          dir .\publish\App_Data\jobs\${{ matrix.type }}
      - name: Restore NuGet Packages
        run: nuget restore ${{ env.SOLUTION_FILE }}
      - name: Build Application (${{ matrix.webjob-name }})
        run: |
          msbuild ${{ matrix.webjob-path }}/PG.LARA.${{ matrix.webjob-name }}.WebJob.csproj `
            /p:DeployOnBuild=true `
            /p:OutputPath=./publish/App_Data/jobs/${{ matrix.webjob-type }}/DEV-${{ matrix.webjob-name }}}
